### ISSUE TITLE
Correção Exercício `0.4.1`

### ISSUE THREAD

**Issue by mathiasgheno** [MCosta093/0.4.2#1]
# Correção Exercício `0.4.1`

> Faça uma tabela que representa os principais influenciados que você acompanha. Essa tabela deve conter pelo menos três influenciados e o acesso de pelo menos duas redes sociais deles. Dentro da celula da rede social deve conter um link para a rede social do influenciador. Você deve utilizar o `nth-child` para definir o cor do cabeçalho e para adicionar um background nas linhas que são ímpar. Além disso, você deve fazer uso do `:hover` para aplicar um background diferente para o `tr`. Por fim, você deve aplicar um estilo único para o link baseado nas cores que são utilizadas na rede social escolhida. Veja [referência visual](https://i.imgur.com/PKzeLtu.png) como inspiração. Você tem liberdade para aplicar mais estilos e diferentes cores. .

Tudo ok.

**Nota:** 10! Parabéns 🥳 

# Comentários

https://github.com/MCosta093/0.4.2/blob/6253607038b5ad45d442d95eb5bf07ede35ff58c/styles.css#L21-L24

Acredito que a aplicagem do `padding` no `hover` não seja um comportamento desejado. 

```css
button:hover {
  background-color: #494949;
}
```

Talvez a aplicagem de um scale?

```css
button {
  color: white;
  border:none;
  border-radius: 5px;
  transition: transform 0.1s linear;
}
button:hover {
  background-color: #494949;
  transform: scale(1.1);
}
```
